package com.braingods.cva.termux;

import android.content.Context;
import android.util.Log;

import java.io.File;
import java.io.FileOutputStream;

/**
 * BootstrapPostInstall
 * ─────────────────────────────────────────────────────────────────────────────
 * Called by TermuxInstaller immediately after the bootstrap ZIP has been
 * extracted and symlinks processed.  Writes config files that are MISSING from
 * the stock Termux bootstrap but are required for CVA's different package name.
 *
 * WHY THIS IS NEEDED
 * ──────────────────
 * The Termux bootstrap binaries (apt, dpkg, bash, ncurses tools) have the string
 *   /data/data/com.termux/files/usr
 * compiled into them.  When those same binaries run inside com.braingods.cva they
 * try to open the real Termux app's files — which Android's app sandbox denies.
 *
 * We cannot patch ELF binary data, but we CAN override paths at runtime via:
 *   • apt    → APT_CONFIG environment variable (set in TermuxEnvironment)
 *   • dpkg   → DPKG_ADMINDIR environment variable (set in TermuxEnvironment)
 *   • ncurses→ TERMINFO environment variable (set in TermuxEnvironment)
 *
 * This class writes the CONFIG FILES those variables point to, so the tools
 * actually find a valid config when they start up.
 *
 * CALL SITE  (in TermuxInstaller, after step 6 — atomic rename)
 * ─────────────────────────────────────────────────────────────
 *   BootstrapPostInstall.run(ctx, cb);
 */
public final class BootstrapPostInstall {

    private static final String TAG = "BootstrapPostInstall";

    /** Callback so TermuxInstaller can report progress to the UI. */
    public interface Callback {
        void onProgress(String message);
    }

    /**
     * Run all post-install fixups.  Safe to call from any background thread.
     * Idempotent — calling multiple times produces the same result.
     */
    public static void run(Context ctx, Callback cb) {
        String prefix = TermuxConstants.PREFIX_PATH;

        cb.onProgress("Configuring apt for CVA prefix…");
        writeAptConf(prefix, cb);

        cb.onProgress("Initialising dpkg database…");
        ensureDpkgDatabase(prefix, cb);

        cb.onProgress("Writing pkg wrapper script…");
        writePkgWrapper(prefix, cb);

        cb.onProgress("Writing terminfo config…");
        writeTerminfoConfig(prefix, cb);

        cb.onProgress("Writing apt sources.list…");
        writeSourcesList(prefix, cb);

        cb.onProgress("Post-install fixup complete ✓");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 1.  apt.conf  — tells apt to use CVA's prefix for everything
    // ─────────────────────────────────────────────────────────────────────────

    private static void writeAptConf(String prefix, Callback cb) {
        // APT_CONFIG env var points here (set in TermuxEnvironment).
        // When apt reads this file it sets Dir to our prefix BEFORE it would
        // otherwise fall back to the com.termux compiled-in default.
        File aptEtc = new File(prefix + "/etc/apt");
        aptEtc.mkdirs();
        new File(aptEtc, "apt.conf.d").mkdirs();

        String content =
                "// CVA apt.conf — generated by BootstrapPostInstall\n" +
                        "// Redirects apt from its compiled-in com.termux prefix to CVA's prefix.\n\n" +

                        "Dir \"" + prefix + "/\";\n" +
                        "Dir::Etc \"" + prefix + "/etc/apt/\";\n" +
                        "Dir::Etc::sourcelist \"sources.list\";\n" +
                        "Dir::Etc::sourceparts \"sources.list.d\";\n" +
                        "Dir::Cache \"" + prefix + "/var/cache/apt/\";\n" +
                        "Dir::Cache::archives \"archives/\";\n" +
                        "Dir::State \"" + prefix + "/var/lib/apt/\";\n" +
                        "Dir::State::status \"" + prefix + "/var/lib/dpkg/status\";\n" +
                        "Dir::Log \"" + prefix + "/var/log/apt/\";\n" +
                        "Dir::Bin::dpkg \"" + prefix + "/bin/dpkg\";\n" +
                        // FIX: apt transports (https/http/ftp) are compiled-in binaries.\n                // apt's default path is /data/data/com.termux/files/usr/lib/apt/methods/\n                // Without this override, `apt update` fails with:\n                //   "The method driver /data/data/com.termux/…/methods/https could not be found."\n                "Dir::Bin::Methods \"" + prefix + "/lib/apt/methods/\";\n\n" +

                        "// Non-interactive installs (no changelog prompts)\n" +
                        "DPkg::Options {\n" +
                        "  \"--force-confdef\";\n" +
                        "  \"--force-confnew\";\n" +
                        "};\n" +
                        "APT::Get::Assume-Yes \"true\";\n" +
                        "APT::Get::AllowUnauthenticated \"true\";\n" +
                        "Acquire::http::No-Cache \"true\";\n";

        writeFile(new File(aptEtc, "apt.conf"), content, cb);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 2.  apt sources.list — Termux's official repository
    // ─────────────────────────────────────────────────────────────────────────

    private static void writeSourcesList(String prefix, Callback cb) {
        File sourcesDir = new File(prefix + "/etc/apt");
        sourcesDir.mkdirs();
        new File(prefix + "/etc/apt/sources.list.d").mkdirs();

        File sourcesList = new File(sourcesDir, "sources.list");
        if (sourcesList.exists() && sourcesList.length() > 10) {
            // Already written by bootstrap extraction — don't clobber
            cb.onProgress("  sources.list already present, skipping");
            return;
        }

        // Termux official repo; packages are pre-built for aarch64/arm/x86_64
        // and work fine via apt when Dir is set correctly.
        String arch = TermuxShellUtils.getArch();
        String termuxArch;
        switch (arch) {
            case "aarch64": termuxArch = "aarch64"; break;
            case "arm":     termuxArch = "arm";     break;
            case "x86_64":  termuxArch = "x86_64";  break;
            default:        termuxArch = "aarch64"; break;
        }

        String content =
                "# CVA sources.list — Termux official repository\n" +
                        "deb https://packages.termux.dev/apt/termux-main stable main\n";

        writeFile(sourcesList, content, cb);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 3.  dpkg database skeleton
    // ─────────────────────────────────────────────────────────────────────────

    private static void ensureDpkgDatabase(String prefix, Callback cb) {
        // dpkg requires these directories and a minimal status file.
        // Without them dpkg exits with "Unable to determine packaging system type".

        String[] dirs = {
                prefix + "/var/lib/dpkg",
                prefix + "/var/lib/dpkg/info",
                prefix + "/var/lib/dpkg/updates",
                prefix + "/var/lib/dpkg/parts",
                prefix + "/var/lib/apt",
                prefix + "/var/lib/apt/lists",
                prefix + "/var/lib/apt/lists/partial",
                prefix + "/var/cache/apt",
                prefix + "/var/cache/apt/archives",
                prefix + "/var/cache/apt/archives/partial",
                prefix + "/var/log/apt",
        };

        for (String dir : dirs) {
            File f = new File(dir);
            if (!f.exists()) {
                f.mkdirs();
                Log.d(TAG, "mkdirs: " + dir);
            }
        }

        // dpkg status file — must exist even if empty
        File status = new File(prefix + "/var/lib/dpkg/status");
        if (!status.exists() || status.length() == 0) {
            writeFile(status,
                    "# dpkg status — managed by CVA BootstrapPostInstall\n", cb);
        }

        // dpkg available file
        File available = new File(prefix + "/var/lib/dpkg/available");
        if (!available.exists()) {
            writeFile(available, "", cb);
        }

        // dpkg lock files (pre-create so dpkg doesn't complain about missing dirs)
        touch(new File(prefix + "/var/lib/dpkg/lock"));
        touch(new File(prefix + "/var/lib/dpkg/lock-frontend"));
        touch(new File(prefix + "/var/cache/apt/archives/lock"));
        touch(new File(prefix + "/var/lib/apt/lists/lock"));
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 4.  pkg wrapper  — Termux users type `pkg install git`, not `apt install git`
    // ─────────────────────────────────────────────────────────────────────────

    private static void writePkgWrapper(String prefix, Callback cb) {
        File binDir = new File(prefix + "/bin");
        File pkgScript = new File(binDir, "pkg");

        // FIX: ALWAYS overwrite the bootstrap's pkg script.
        // The Termux bootstrap ships /usr/bin/pkg with hardcoded internal references
        // to /data/data/com.termux/... paths (not just the shebang line).
        // For example, line 11 calls:
        //   /data/data/com.termux/files/usr/bin/termux-setup-package-manager
        // patchShebangs() only rewrites the first #!/ line — it misses all
        // subsequent references to com.termux inside the script body.
        // We write our clean CVA wrapper unconditionally to replace it.
        if (pkgScript.exists()) {
            cb.onProgress("  Replacing bootstrap pkg script (may have com.termux refs)…");
        }

        // A minimal pkg wrapper that delegates to apt-get with the right flags.
        // Covers the commands users type most: install, remove, update, upgrade,
        // search, show, list-installed, reinstall, clean.
        String content =
                "#!" + prefix + "/bin/bash\n" +
                        "# CVA pkg wrapper — generated by BootstrapPostInstall\n" +
                        "# Mirrors Termux's pkg script: delegates to apt-get / dpkg.\n\n" +

                        "export APT_CONFIG=\"" + prefix + "/etc/apt/apt.conf\"\n" +
                        "export DPKG_ADMINDIR=\"" + prefix + "/var/lib/dpkg\"\n" +
                        "export DEBIAN_FRONTEND=noninteractive\n\n" +

                        "CMD=\"$1\"; shift\n\n" +

                        "case \"$CMD\" in\n" +
                        "  install|add)\n" +
                        "    \"" + prefix + "/bin/apt-get\" install -y \"$@\" ;;\n" +
                        "  remove|uninstall)\n" +
                        "    \"" + prefix + "/bin/apt-get\" remove -y \"$@\" ;;\n" +
                        "  update)\n" +
                        "    \"" + prefix + "/bin/apt-get\" update ;;\n" +
                        "  upgrade)\n" +
                        "    \"" + prefix + "/bin/apt-get\" upgrade -y \"$@\" ;;\n" +
                        "  full-upgrade|dist-upgrade)\n" +
                        "    \"" + prefix + "/bin/apt-get\" full-upgrade -y \"$@\" ;;\n" +
                        "  search)\n" +
                        "    \"" + prefix + "/bin/apt-cache\" search \"$@\" ;;\n" +
                        "  show|info)\n" +
                        "    \"" + prefix + "/bin/apt-cache\" show \"$@\" ;;\n" +
                        "  list-installed)\n" +
                        "    \"" + prefix + "/bin/dpkg\" -l ;;\n" +
                        "  reinstall)\n" +
                        "    \"" + prefix + "/bin/apt-get\" install --reinstall -y \"$@\" ;;\n" +
                        "  clean)\n" +
                        "    \"" + prefix + "/bin/apt-get\" clean ;;\n" +
                        "  autoclean)\n" +
                        "    \"" + prefix + "/bin/apt-get\" autoclean ;;\n" +
                        "  autoremove)\n" +
                        "    \"" + prefix + "/bin/apt-get\" autoremove -y ;;\n" +
                        "  files)\n" +
                        "    \"" + prefix + "/bin/dpkg\" -L \"$@\" ;;\n" +
                        "  *)\n" +
                        "    echo \"CVA pkg — usage:\"\n" +
                        "    echo \"  pkg install <pkg>      install a package\"\n" +
                        "    echo \"  pkg remove <pkg>       remove a package\"\n" +
                        "    echo \"  pkg update             update package lists\"\n" +
                        "    echo \"  pkg upgrade            upgrade all packages\"\n" +
                        "    echo \"  pkg search <term>      search available packages\"\n" +
                        "    echo \"  pkg show <pkg>         show package info\"\n" +
                        "    echo \"  pkg list-installed     list installed packages\"\n" +
                        "    echo \"  pkg files <pkg>        list files in package\"\n" +
                        "    echo \"  pkg clean              clear download cache\"\n" +
        "esac\n";

        writeFile(pkgScript, content, cb);
        pkgScript.setExecutable(true, false);

        // Also ensure apt-get is executable (sometimes lost in extraction)
        new File(binDir, "apt-get").setExecutable(true, false);
        new File(binDir, "apt").setExecutable(true, false);
        new File(binDir, "dpkg").setExecutable(true, false);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 5.  terminfo config  — ncurses search path
    // ─────────────────────────────────────────────────────────────────────────

    private static void writeTerminfoConfig(String prefix, Callback cb) {
        // ncurses reads /etc/terminfo.conf (or TERMINFO env) for the database path.
        // The env var is set in TermuxEnvironment; this writes the fallback config.
        File etcDir = new File(prefix + "/etc");
        etcDir.mkdirs();

        File conf = new File(etcDir, "terminfo.conf");
        if (!conf.exists()) {
            String content =
                    "# ncurses terminfo search path — CVA BootstrapPostInstall\n" +
                            prefix + "/share/terminfo\n";
            writeFile(conf, content, cb);
        }

        // Ensure the terminfo directory exists (bootstrap should have it)
        new File(prefix + "/share/terminfo").mkdirs();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Utilities
    // ─────────────────────────────────────────────────────────────────────────

    private static void writeFile(File f, String content, Callback cb) {
        try {
            f.getParentFile().mkdirs();
            try (FileOutputStream fos = new FileOutputStream(f)) {
                fos.write(content.getBytes("UTF-8"));
            }
            Log.d(TAG, "wrote: " + f.getAbsolutePath());
        } catch (Exception e) {
            Log.w(TAG, "writeFile failed (" + f.getName() + "): " + e.getMessage());
            if (cb != null) cb.onProgress("  warn: could not write " + f.getName());
        }
    }

    private static void touch(File f) {
        if (!f.exists()) {
            try {
                f.getParentFile().mkdirs();
                f.createNewFile();
            } catch (Exception ignored) {}
        }
    }

    private BootstrapPostInstall() {}
}