package com.braingods.cva.termux;

import android.app.Application;
import android.content.Context;
import android.util.Log;

import java.io.File;
import java.util.concurrent.Executors;

/**
 * TermuxApplication
 * ─────────────────────────────────────────────────────────────────────────────
 * Mirrors Termux's TermuxApplication.  Performs one-time bootstrap setup
 * on first launch.
 *
 * HOW TO USE:
 *   Option A — Let your existing Application class delegate to this:
 *
 *     public class MyApp extends Application {
 *         @Override
 *         public void onCreate() {
 *             super.onCreate();
 *             TermuxApplication.onAppCreate(this);
 *             // ... rest of your app init
 *         }
 *     }
 *
 *   Option B — Just call TermuxApplication.onAppCreate(context) from
 *   your MainActivity.onCreate() before binding TerminalService.
 *
 * WHAT THIS DOES:
 *   1. Creates PREFIX, HOME, TMPDIR directories
 *   2. Checks if bootstrap is installed
 *   3. If NOT installed — queues a background download (silent first time)
 *   4. Sets TERM, LANG, PATH environment hints (via system properties on
 *      Android is not possible, but we write them to .profile so the shell
 *      sources them immediately on start)
 */
public class TermuxApplication {

    private static final String TAG = "TermuxApplication";

    private static volatile boolean initialized = false;

    /** Call this from Application.onCreate() or MainActivity.onCreate(). */
    public static void onAppCreate(Context ctx) {
        if (initialized) return;
        initialized = true;

        Log.d(TAG, "Initialising Termux-compatible environment");

        // Ensure directory tree exists
        TermuxShellUtils.ensureDirectories();

        // Check bootstrap state
        boolean bootstrapOk = TermuxShellUtils.isCvaBootstrapInstalled();
        boolean termuxOk    = TermuxShellUtils.isTermuxInstalled();

        Log.d(TAG, "Bootstrap installed: " + bootstrapOk);
        Log.d(TAG, "Real Termux present: " + termuxOk);
        Log.d(TAG, "Device ABI: " + TermuxShellUtils.getArch());

        if (!bootstrapOk && !termuxOk) {
            // Silently pre-check only — actual install is triggered by TerminalManager
            // when the user opens the terminal for the first time.
            Log.d(TAG, "Bootstrap not installed — will install on first terminal open");
        }

        // Write /data/data/com.braingods.cva/files/home/.profile
        // so ANY shell (even /system/bin/sh) sources our environment on login.
        writeSystemProfile(ctx);
    }

    /**
     * Writes a .profile to HOME that any POSIX shell will source on login.
     * This ensures PATH and TERM are always correct regardless of which
     * shell ends up running.
     */
    private static void writeSystemProfile(Context ctx) {
        File home = new File(TermuxConstants.HOME_PATH);
        if (!home.exists()) home.mkdirs();

        File profile = new File(home, ".profile");
        String prefix  = TermuxConstants.PREFIX_PATH;
        String homePath = TermuxConstants.HOME_PATH;

        String content =
                "# CVA .profile — auto-generated by TermuxApplication\n" +
                        "export PREFIX=\"" + prefix + "\"\n" +
                        "export HOME=\"" + homePath + "\"\n" +
                        "export TMPDIR=\"" + prefix + "/tmp\"\n" +
                        "export TERM=xterm-256color\n" +
                        "export COLORTERM=truecolor\n" +
                        "export LANG=en_US.UTF-8\n" +
                        "export PATH=\"/system/bin:/system/xbin:" + prefix + "/bin\"\n" +
                        "export LD_LIBRARY_PATH=\"" + prefix + "/lib\"\n" +
                        // APT_CONFIG: redirect apt away from compiled-in com.termux paths
                        // Written unconditionally — BootstrapPostInstall creates the file.
                        "export APT_CONFIG=\"" + prefix + "/etc/apt/apt.conf\"\n" +
                        "export DPKG_ADMINDIR=\"" + prefix + "/var/lib/dpkg\"\n" +
                        "export DEBIAN_FRONTEND=noninteractive\n" +
                        "export APT_LISTCHANGES_FRONTEND=none\n" +
                        // TERMINFO: redirect ncurses away from compiled-in com.termux paths
                        // Without this, nano/vim/tmux crash with "cannot initialize terminal type"
                        "export TERMINFO=\"" + prefix + "/share/terminfo\"\n" +
                        "export TERMINFO_DIRS=\"" + prefix + "/share/terminfo:/system/lib/terminfo\"\n" +
                        "[ -f $HOME/.bashrc ] && . $HOME/.bashrc\n";

        try (java.io.FileOutputStream fos = new java.io.FileOutputStream(profile)) {
            fos.write(content.getBytes("UTF-8"));
            Log.d(TAG, ".profile written to " + profile.getAbsolutePath());
        } catch (Exception e) {
            Log.w(TAG, ".profile write failed: " + e.getMessage());
        }
    }

    private TermuxApplication() {}
}